version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: flask_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: flask
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppass"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: todo_flask
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

volumes:
  db_data:
